--
-- Script para importar datos de prueba
-- github.com/fernandocalmet
--
INSERT INTO Modules (name) VALUES ('Modules');
INSERT INTO Modules (name) VALUES ('Operations');
INSERT INTO Operations (name, id_module) VALUES ('Create operation', 2);
INSERT INTO Operations (name, id_module) VALUES ('Delete operation', 2);
INSERT INTO Operations (name, id_module) VALUES ('Details operation', 2);
INSERT INTO Operations (name, id_module) VALUES ('Update operation', 2);
INSERT INTO Operations (name, id_module) VALUES ('List operations', 2);
INSERT INTO Operations (name, id_module) VALUES ('Create role', 2);
INSERT INTO Operations (name, id_module) VALUES ('Delete role', 2);
INSERT INTO Operations (name, id_module) VALUES ('Details role', 2);
INSERT INTO Operations (name, id_module) VALUES ('Update role', 2);
INSERT INTO Operations (name, id_module) VALUES ('List roles', 2);
INSERT INTO Operations (name, id_module) VALUES ('Create permission', 2);
INSERT INTO Operations (name, id_module) VALUES ('Delete permission', 2);
INSERT INTO Operations (name, id_module) VALUES ('Details permission', 2);
INSERT INTO Operations (name, id_module) VALUES ('Update permission', 2);
INSERT INTO Operations (name, id_module) VALUES ('List permissions', 2);
INSERT INTO Operations (name, id_module) VALUES ('Create user', 2);
INSERT INTO Operations (name, id_module) VALUES ('Delete user', 2);
INSERT INTO Operations (name, id_module) VALUES ('Details user', 2);
INSERT INTO Operations (name, id_module) VALUES ('Update user', 2);
INSERT INTO Operations (name, id_module) VALUES ('List users', 2);
INSERT INTO Operations (name, id_module) VALUES ('Create module', 1);
INSERT INTO Operations (name, id_module) VALUES ('Delete module', 1);
INSERT INTO Operations (name, id_module) VALUES ('Details module', 1);
INSERT INTO Operations (name, id_module) VALUES ('Update module', 1);
INSERT INTO Operations (name, id_module) VALUES ('List modules', 1);
INSERT INTO Roles (name) VALUES ('Developer');
INSERT INTO Roles (name) VALUES ('Administrator');
INSERT INTO Roles (name) VALUES ('Supervisor');
INSERT INTO Roles (name) VALUES ('Client');
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 1);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 2);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 3);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 4);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 5);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 6);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 7);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 8);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 9);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 10);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 11);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 12);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 13);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 14);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 15);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 16);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 17);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 18);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 19);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 20);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 21);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 22);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 23);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 24);
INSERT INTO Permissions (id_role, id_operation) VALUES (1, 25);
INSERT INTO Permissions (id_role, id_operation) VALUES (2, 3);
INSERT INTO Permissions (id_role, id_operation) VALUES (2, 5);
INSERT INTO Permissions (id_role, id_operation) VALUES (2, 8);
INSERT INTO Permissions (id_role, id_operation) VALUES (2, 10);
INSERT INTO Permissions (id_role, id_operation) VALUES (2, 13);
INSERT INTO Permissions (id_role, id_operation) VALUES (2, 15);
INSERT INTO Permissions (id_role, id_operation) VALUES (2, 18);
INSERT INTO Permissions (id_role, id_operation) VALUES (2, 20);
INSERT INTO Permissions (id_role, id_operation) VALUES (3, 3);
INSERT INTO Permissions (id_role, id_operation) VALUES (3, 5);
INSERT INTO Permissions (id_role, id_operation) VALUES (3, 8);
INSERT INTO Permissions (id_role, id_operation) VALUES (3, 10);
INSERT INTO Permissions (id_role, id_operation) VALUES (3, 13);
INSERT INTO Permissions (id_role, id_operation) VALUES (3, 15);
INSERT INTO Permissions (id_role, id_operation) VALUES (3, 18);
INSERT INTO Permissions (id_role, id_operation) VALUES (3, 20);
INSERT INTO Users (id_role, email, password, name) VALUES (1, 'fercalmet@gmail.com', '12345678', 'Fernando Calmet');